//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fall2020_CSC403_Project.Cosmetics {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CosmeticsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CosmeticsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fall2020_CSC403_Project.Cosmetics.CosmeticsResources", typeof(CosmeticsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Foam Cowboy Hat&quot;,
        ///    &quot;XCoordinate&quot;: 1,
        ///    &quot;YCoordinate&quot;: 1,
        ///    &quot;ImageResourceName&quot;: &quot;hat_foam_image&quot;
        ///}.
        /// </summary>
        public static string hat_foam {
            get {
                return ResourceManager.GetString("hat_foam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hat_foam_image {
            get {
                object obj = ResourceManager.GetObject("hat_foam_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Shrek Hat&quot;,
        ///    &quot;XCoordinate&quot;: 1,
        ///    &quot;YCoordinate&quot;: 1,
        ///    &quot;ImageResourceName&quot;: &quot;hat_shrek_image&quot;
        ///}.
        /// </summary>
        public static string hat_shrek {
            get {
                return ResourceManager.GetString("hat_shrek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hat_shrek_image {
            get {
                object obj = ResourceManager.GetObject("hat_shrek_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Skyrim Helmet&quot;,
        ///    &quot;XCoordinate&quot;: 1,
        ///    &quot;YCoordinate&quot;: 2,
        ///    &quot;ImageResourceName&quot;: &quot;hat_skyrimhelmet_image&quot;
        ///}.
        /// </summary>
        public static string hat_skyrimhelmet {
            get {
                return ResourceManager.GetString("hat_skyrimhelmet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hat_skyrimhelmet_image {
            get {
                object obj = ResourceManager.GetObject("hat_skyrimhelmet_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Steve Mincreaft Head&quot;,
        ///    &quot;XCoordinate&quot;: 1,
        ///    &quot;YCoordinate&quot;: 1,
        ///    &quot;ImageResourceName&quot;: &quot;hat_steveminecrafthead_image&quot;
        ///}.
        /// </summary>
        public static string hat_steveminecrafthead {
            get {
                return ResourceManager.GetString("hat_steveminecrafthead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hat_steveminecrafthead_image {
            get {
                object obj = ResourceManager.GetObject("hat_steveminecrafthead_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Name&quot;: &quot;Tin Foil Hat&quot;,
        ///    &quot;XCoordinate&quot;: 1,
        ///    &quot;YCoordinate&quot;: 1,
        ///    &quot;ImageResourceName&quot;: &quot;hat_tinfoil_image&quot;
        ///}.
        /// </summary>
        public static string hat_tinfoil {
            get {
                return ResourceManager.GetString("hat_tinfoil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hat_tinfoil_image {
            get {
                object obj = ResourceManager.GetObject("hat_tinfoil_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
